owner: skyfrk-bot
repo: upptime

sites:
  - name: esslinger.dev
    url: https://esslinger.dev
  - name: RSS Reader
    url: $RSS_READER_URL
  - name: Teamspeak 3 Server
    url: $TS3_HC_URL
    
assignees:
  - skyfrk

status-website:
  cname: status.esslinger.dev
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: esslinger.dev
      href: https://esslinger.dev
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: skyfrk-bot
commitMessages:
  commitAuthorName: skyfrk-bot
  commitAuthorEmail: skyfrk-bot@users.noreply.github.com
